<a href="https://colab.research.google.com/github/Jultromix/PAI-PROJECT/blob/main/Udemy_Course/(ANN)_Udemy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Text Format
## Heading 2
### Heading 3



---
* This is a common code description!

* For using Latex (as description or explanations of functions/ artyhmetics) use the following reference: https://colab.research.google.com/github/bebi103a/bebi103a.github.io/blob/master/lessons/00/intro_to_latex.ipynb

Normal text.



# Curiosities
Tuples with mutable items, remain as unmutable objects while its items if mutable, may be modified when accessing them directly

In [ ]:
colors=["red","green","blue"]
spectrum=(colors,255,"spectrum")
print(spectrum)

(['red', 'green', 'blue'], 255, 'spectrum')


In [ ]:
colors[0]="brown"
print(spectrum)

(['brown', 'green', 'blue'], 255, 'spectrum')


In [ ]:
spectrum[0][0]="red"
print(spectrum)    

(['red', 'green', 'blue'], 255, 'spectrum')


# Numpy library

In [ ]:
import numpy as np

vec1 = np.array([1,2,3])
vec2 = np.array([[1]])
vec3 = np.array([[1,2],[3,4]])

In [ ]:
print(vec1)
print(vec2)
print(vec3)

[1 2 3]
[[1]]
[[1 2]
 [3 4]]


In [ ]:
print(vec1.shape)
print(vec2.shape)
print(vec3.shape)

(3,)
(1, 1)
(2, 2)


In [ ]:
np.random.rand(4,4)

array([[0.82581742, 0.30662338, 0.10677141, 0.68058961],
       [0.25901933, 0.24755399, 0.94377315, 0.86066906],
       [0.35543992, 0.26379613, 0.58181737, 0.18444887],
       [0.46879844, 0.16432161, 0.27129283, 0.35238108]])

In [ ]:
np.arange(4,20,4)

array([ 4,  8, 12, 16])

In [ ]:
np.random.randn(4,4)

array([[ 0.74930464, -0.39285931, -0.54036413,  1.73577715],
       [ 0.30656989,  0.90393324,  3.08808065,  0.73888231],
       [ 0.58296406, -0.14430144, -0.86323987, -0.33835629],
       [-0.42282871, -1.81746182, -0.64828232,  1.72032502]])

# Pandas

First lets import a repository and work from there to access files (also to learn how to commit and pull changes to github)

Console commands:

* !rm -rf   <---(remove folder)
* !rm       <---(remove file/folder)
* %cd       <---(change directory)
* %ls       <---(list files)
* !mv       <---(move file/folder)

In [2]:
!git config --global user.name "Jultromix"
!git config --global user.email "juliomoreno7217@gmail.com"


In [3]:
token = ""
username = "Jultromix"
repo = "PAI-PROJECT"

In [4]:
!git clone https://github.com/{username}/{repo}

Cloning into 'PAI-PROJECT'...
remote: Enumerating objects: 33, done.
remote: Counting objects: 100% (33/33), done.
remote: Compressing objects: 100% (30/30), done.
remote: Total 33 (delta 11), reused 10 (delta 3), pack-reused 0
Unpacking objects: 100% (33/33), done.


In [5]:
%cd PAI-PROJECT/

/content/PAI-PROJECT
