<a href="https://colab.research.google.com/github/Jultromix/PAI-PROJECT/blob/main/Udemy_Course/(ANN)_Udemy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Text Format
## Heading 2
### Heading 3



---
* This is a common code description!

* For using Latex (as description or explanations of functions/ artyhmetics) use the following reference: https://colab.research.google.com/github/bebi103a/bebi103a.github.io/blob/master/lessons/00/intro_to_latex.ipynb

Normal text.



# Curiosities
Tuples with mutable items, remain as unmutable objects while its items if mutable, may be modified when accessing them directly

In [ ]:
colors=["red","green","blue"]
spectrum=(colors,255,"spectrum")
print(spectrum)

(['red', 'green', 'blue'], 255, 'spectrum')


In [ ]:
colors[0]="brown"
print(spectrum)

(['brown', 'green', 'blue'], 255, 'spectrum')


In [ ]:
spectrum[0][0]="red"
print(spectrum)    

(['red', 'green', 'blue'], 255, 'spectrum')


# Numpy library

In [ ]:
import numpy as np

vec1 = np.array([1,2,3])
vec2 = np.array([[1]])
vec3 = np.array([[1,2],[3,4]])

In [ ]:
print(vec1)
print(vec2)
print(vec3)

[1 2 3]
[[1]]
[[1 2]
 [3 4]]


In [ ]:
print(vec1.shape)
print(vec2.shape)
print(vec3.shape)

(3,)
(1, 1)
(2, 2)


In [ ]:
np.random.rand(4,4)

array([[0.82581742, 0.30662338, 0.10677141, 0.68058961],
       [0.25901933, 0.24755399, 0.94377315, 0.86066906],
       [0.35543992, 0.26379613, 0.58181737, 0.18444887],
       [0.46879844, 0.16432161, 0.27129283, 0.35238108]])

In [ ]:
np.arange(4,20,4)

array([ 4,  8, 12, 16])

In [ ]:
np.random.randn(4,4)

array([[ 0.74930464, -0.39285931, -0.54036413,  1.73577715],
       [ 0.30656989,  0.90393324,  3.08808065,  0.73888231],
       [ 0.58296406, -0.14430144, -0.86323987, -0.33835629],
       [-0.42282871, -1.81746182, -0.64828232,  1.72032502]])

# Pandas

First lets import a repository and work from there to access files (also to learn how to commit and pull changes to github)

Console commands:

* !rm -rf   <---(remove folder)
* !rm       <---(remove file/folder)
* %cd       <---(change directory)
* %ls       <---(list files)
* !mv       <---(move file/folder)

For more console commands here there's a web page showing them in detail: https://ipython.readthedocs.io/en/stable/interactive/magics.html#magic-cd

In [25]:
!git config --global user.name "Julio Moreno"
!git config --global user.email "julio.morenoshz@uanl.edu.mx"
!git config --global user.password "$_Pass_tronica2001_word"


In [27]:
#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
token = "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"
username = "Jultromix"
repo = "PAI-PROJECT"

In [28]:
!git clone https://{token}@github.com/{username}/{repo}

Cloning into 'PAI-PROJECT'...
remote: Enumerating objects: 37, done.
remote: Counting objects: 100% (37/37), done.
remote: Compressing objects: 100% (33/33), done.
remote: Total 37 (delta 13), reused 10 (delta 3), pack-reused 0
Unpacking objects: 100% (37/37), done.


In [29]:
%cd PAI-PROJECT/

/content/PAI-PROJECT


In [30]:
import pandas as pd


In [31]:
!git add -A

In [35]:
!git add -A

In [36]:
!git status

On branch main
Your branch is up to date with 'origin/main'.

Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	new file:   Udemy_Course/Customer.csv
	new file:   Udemy_Course/Product.txt



In [37]:
!git commit -m "pandas files added"

[main b3cda03] pandas files added
 2 files changed, 2657 insertions(+)
 create mode 100644 Udemy_Course/Customer.csv
 create mode 100644 Udemy_Course/Product.txt


In [39]:
!git push origin main

Counting objects: 5, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 55.89 KiB | 6.21 MiB/s, done.
Total 5 (delta 1), reused 0 (delta 0)
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
To https://github.com/Jultromix/PAI-PROJECT
   d522266..b3cda03  main -> main


In [40]:
%cd /content/PAI-PROJECT/Udemy_Course

/content/PAI-PROJECT/Udemy_Course


# Accesing data-files 
'til now everything goes fine:

In [44]:
data1 = pd.read_csv("/content/PAI-PROJECT/Udemy_Course/Customer.csv",header=0)
data1.head(10) #number of rows displayed

Customer ID       Customer Name      Segment  Age        Country  \
0    CG-12520         Claire Gute     Consumer   67  United States   
1    DV-13045     Darrin Van Huff    Corporate   31  United States   
2    SO-20335      Sean O'Donnell     Consumer   65  United States   
3    BH-11710     Brosina Hoffman     Consumer   20  United States   
4    AA-10480        Andrew Allen     Consumer   50  United States   
5    IM-15070        Irene Maddox     Consumer   66  United States   
6    HP-14815       Harold Pawlan  Home Office   20  United States   
7    PK-19075           Pete Kriz     Consumer   46  United States   
8    AG-10270     Alejandro Grove     Consumer   18  United States   
9    ZD-21925  Zuschuss Donatelli     Consumer   66  United States   

              City           State  Postal Code   Region  
0        Henderson        Kentucky        42420    South  
1      Los Angeles      California        90036     West  
2  Fort Lauderdale         Florida        33311    South  
3      Los Angeles      California        90032     West  
4          Concord  North Carolina        28027    South  
5          Seattle      Washington        98103     West  
6       Fort Worth           Texas        76106  Central  
7          Madison       Wisconsin        53711  Central  
8      West Jordan            Utah        84084     West  
9    San Francisco      California        94109     West

"index_col" sets a given column as the index column, in the process some columns can be dropped.

In [46]:
data2 = pd.read_csv("/content/PAI-PROJECT/Udemy_Course/Customer.csv",header=0,index_col=0)
data2.head(10) #number of rows displayed

Customer Name      Segment  Age        Country  \
Customer ID                                                        
CG-12520            Claire Gute     Consumer   67  United States   
DV-13045        Darrin Van Huff    Corporate   31  United States   
SO-20335         Sean O'Donnell     Consumer   65  United States   
BH-11710        Brosina Hoffman     Consumer   20  United States   
AA-10480           Andrew Allen     Consumer   50  United States   
IM-15070           Irene Maddox     Consumer   66  United States   
HP-14815          Harold Pawlan  Home Office   20  United States   
PK-19075              Pete Kriz     Consumer   46  United States   
AG-10270        Alejandro Grove     Consumer   18  United States   
ZD-21925     Zuschuss Donatelli     Consumer   66  United States   

                        City           State  Postal Code   Region  
Customer ID                                                         
CG-12520           Henderson        Kentucky        42420    South  
DV-13045         Los Angeles      California        90036     West  
SO-20335     Fort Lauderdale         Florida        33311    South  
BH-11710         Los Angeles      California        90032     West  
AA-10480             Concord  North Carolina        28027    South  
IM-15070             Seattle      Washington        98103     West  
HP-14815          Fort Worth           Texas        76106  Central  
PK-19075             Madison       Wisconsin        53711  Central  
AG-10270         West Jordan            Utah        84084     West  
ZD-21925       San Francisco      California        94109     West

In [48]:
print(type(data1.describe()))
data1.describe()

<class 'pandas.core.frame.DataFrame'>


Age   Postal Code
count  793.000000    793.000000
mean    44.467844  55229.717528
std     15.526673  31679.223816
min     18.000000   1841.000000
25%     31.000000  27217.000000
50%     45.000000  55901.000000
75%     58.000000  90004.000000
max     70.000000  99207.000000

A function to get info given a key index: iloc nad loc:

Similar to python lists in which you may access items' index through their name (.loc()) or through an index get the contetn stored (.iloc()), this index can also be a range of numbers. 

In [52]:
data1.iloc[2]

Customer ID             SO-20335
Customer Name     Sean O'Donnell
Segment                 Consumer
Age                           65
Country            United States
City             Fort Lauderdale
State                    Florida
Postal Code                33311
Region                     South
Name: 2, dtype: object

In [53]:
data2.loc["DV-13045"]

Customer Name    Darrin Van Huff
Segment                Corporate
Age                           31
Country            United States
City                 Los Angeles
State                 California
Postal Code                90036
Region                      West
Name: DV-13045, dtype: object